version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: inko75/kittygram_backend
    env_file:
      - ./backend/kittygram_backend/.env
      - .env_db
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
    expose:
      - 8000
  frontend:
    image: inko75/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: inko75/kittygram_gateway
    env_file:
      - ./backend/kittygram_backend/.env
    ports:
      - 9000:80 
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend

